### ISSUE TITLE
Pass params in animation functions

### ISSUE THREAD

**Issue by lbineau** [geoffgraham/animate.scss#49]
Hi, thanks for your library I use it on several projects, it is already a big improvement compare to the CSS version.
I would want to go further and be able to customize animation functions. (https://www.sitepoint.com/using-sass-maps/#module-configuration)
Something like this (not tested though):
```scss
// in animate.scss files
@include keyframes(fadeInRightBig, $options: ()) {
	$configuration: map-merge((
		tx: 2000px,
	), $options);
	0% {
		opacity: 0;
		@include transform(translateX(map-get($configuration, tx)));
	}
	100% {
		opacity: 1;
		@include transform(translateX(0));
	}
}
// in user scss file
.description {
	@include fadeInRightBig($duration: 1s, $options: (tx: 100%));
}
```

For now I override the animation locally like the following but it feels wrong because it overrides the function for every later uses
```scss
// in user scss file
@include keyframes(fadeInRightBig) {
	0% {
		opacity: 0;
		@include transform(translateX(100%));
	}
	100% {
		opacity: 1;
		@include transform(translateX(0));
	}
}
.description {
	@include fadeInRightBig($duration: 1s);
}
```

What do you think ?
